### ISSUE TITLE
Shape passing xone validation, where it should not.

### ISSUE THREAD

**Issue by rmfranken** [TopQuadrant/shacl#120]
While using the SHACL shapes graph to validate shacl shapes, I found that a shape in my graph passed the validation, where it should not. Namely, that a shape can not be a nodeshape and a propertyshape at the same time, as stated in the graph: 

```
sh:xone ;

 

    sh:targetObjectsOf sh:node ;        # node-node
    sh:targetObjectsOf sh:not ;         # not-node
    sh:targetObjectsOf sh:property ;    # property-node
    sh:targetObjectsOf sh:qualifiedValueShape ; # qualifiedValueShape-node

 

    **# Shapes are either node shapes or property shapes**

 

    sh:xone ( shsh:NodeShapeShape shsh:PropertyShapeShape ) ;
```

 

I had an erroneous shape in my graph which was typed as both a propertyshape and a nodeshape, and the validation report passed no errors. I would expect a resulterror message such as: "Value has 2 shapes out of 2 in the sh:xone enumeration", or at least an sh:path maxcount violation. :

 

My shape:

 

```
ex:myShape a sh:NodeShape,
        sh:PropertyShape ;
    sh:class ex:myclass ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:path ex:myproperty ;
    sh:property ex:anotherproperty ;
    sh:targetClass ex:anotherclass.

 

```
The NodeShapeShape with nodeshape path max count of 0:
```
shsh:NodeShapeShape
    a sh:NodeShape ;
    sh:targetObjectsOf sh:node ;        # node-node
    sh:property [
        sh:path sh:path ;
        sh:maxCount 0 ;                 # NodeShape-path-maxCount
    ] ;

 

```

 Upon inspecting the spec more closely with a colleague, we noticed that there is no targetclass attached to the nodeshapeshape and propertyshapeshape, and that if the sh:targetClass sh:NodeShape resp. sh:PropertyShape were added to the Nodeshapeshape and Propertyshapeshape respectively, the erroneous shape no longer passes validation (as expected, with a sh:path error) It seems right now that none of the limitations on a nodeshapeshape are actually checked on nodeshapes, since there is no target class declaration. Alterntively, sh:targetSubjectsOf sh:targetClass ; could be used, but we are also not sure what is the best way to solve this.

Are we missing something?

**Comment by HolgerKnublauch** [comment]
I guess that's because shsh:PropertyShapeShape and shsh:NodeShapeShape do not verify the rdf:type triples, so having ?s rdf:type sh:NodeShape, sh:PropertyShape is not violating any of the provided shapes. We may have missed this particular case because rdf:type triples in shapes are optional, and expressing all this within SHACL Core was probably too hard.

Let's be honest that the shapes in https://www.w3.org/TR/shacl/#shacl-shacl are not offering complete coverage and never were intended to do that. They were a small side project at the very last week of the W3C working group, because one of the reviewers suggested we integrate something like that. I wouldn't be surprised if those shapes don't work perfectly - the whole WG was under severe time pressure at that stage, including multiple formal objections etc. So feel free to use your own shapes augmenting or replacing the provided shsh shapes.

**Comment by rmfranken** [comment]
Closing this issue as I've been using my own branched version attached for those interested.
[shacl-shacl-fork.txt](https://github.com/TopQuadrant/shacl/files/10543929/shacl-shacl-fork.txt)

**Comment by afs** [comment]
@rmfranken Worth posting that improved shacl-shacl to the community group? And/or discord?

**Comment by rmfranken** [comment]
Sure, I'll post it on discord. Not sure about the community group, where do I access that?
