### ISSUE TITLE
New release (to address vulnerable dependencies)?

### ISSUE THREAD

**Issue by costas80** [TopQuadrant/shacl#123]
I'm posting this as a follow-up to [the PR I made earlier today](https://github.com/TopQuadrant/shacl/pull/122) which has been merged to master (thanks!). The issue at hand was the bump of Jena to 4.2.0 to address CVE-2021-39239.

Do you have a view on when a new TopBraid release would be available that would include this fix?

**Comment by HolgerKnublauch** [comment]
This is becoming a surprisingly tricky topic. As background, this API was meant as reference implementation of SHACL. We are also using a copy of this library in our own product, TopBraid EDG. Code maintenance of the public API only makes sense for us when we can basically use the same source code. Otherwise, we have no realistic way of testing the API for the real world. I have no idea what the open source users are doing.

Over the years however the two copied became severely out of synch. On the product we have moved the SHACL-JS support into separate packages which are no longer under org.topbraid.shacl. This is probably a good thing because upgrading to Java 11 was causing issues between Nashorn and GraalVM. While I don't know if anyone relies on SHACL-JS support, it is still something that will be lost moving forward.

We have also introduced quite a number of built-in constraints (in the tosh.ttl) file which can be used for schema validation, e.g. checking whether shape declarations are actually correct or not. These may or may not be desirable for the open source users, I just don't know.

So I have prepared a shacl-1.4.0 branch that has the code that we also use in the product right now, but I am not quite sure yet when and whether to publish that version.

To be honest, the best outcome would be if someone from the open source community helps/takes ownership of this project here. I'd be more than happy to contribute updates of the functionality, yet I find it increasingly difficult to handle the whole questions of implications for the builds and maven while I am not really using the open source library myself in this current form.

Any volunteers, and how would I find them?

**Comment by griddigit** [comment]
Hi Holger,
It is very good topic for discussion. I have a question related to this. I know Jena SHACL package was updated in the last 1-2 years. Is there some estimate of a "gap" analysis between Jena SHACL package and TopQuadrant SHACL API? I mean what are the key functionalities that TopQuadrant SHACL API brings on top of Jena? if this is kind of known, maybe there is a way to integrate this in Jena SHACL package and have the bigger community taking care of maintenance and further development.

**Comment by HolgerKnublauch** [comment]
The main gaps are in the SHACL-AF (Advanced Features): https://w3c.github.io/shacl/shacl-af/

Andy would know best but I assume Jena-SHACL doesn't support SHACL inferencing rules, node expressions and user-defined SPARQL functions.

At this stage the TopBraid SHACL API has played its part in the evolution and it doesn't need to remain in its current role. If someone wants to add the missing features to Jena then this is fine for me. However, if the TopBraid SHACL API whithers away then the SHACL-AF features will have little support moving forward. We see huge value in the inferencing rules, sh:values in particular.

The Jena SHACL API was created only very recently and "our" implementation has various optimizations that are relevant for our product, so there is no way for us to switch, but that shouldn't bother anyone.

**Comment by costas80** [comment]
Hi @HolgerKnublauch , I think it will take some time to find people to take over the open source project or see if, what and how gets merged to Jena SHACL. Regarding your point on when and whether to publish a new release I think that when a high risk vulnerability comes up it is a good point to do so. The problem here is that the fix would require moving from Jena 3 to 4 which is very risky if you don't know exactly how TopBraid would be affected.

Do you think that a 1.4.0 release published now would be potentially unstable? In parallel to this the search for further people to help with maintenance and further development of course could and should proceed.

**Comment by HolgerKnublauch** [comment]
Which features here do you need that are not covered by jena-shacl?

**Comment by costas80** [comment]
We (the [Interoperability Test Bed team](https://joinup.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed) at the European Commission) provide a generic SHACL validator that can be used with any shapes to validate RDF. So basically if a user makes use of SHACL-AF features these would not be supported with Jena SHACL. Also we can't know if among our users we have any such cases. We have users (projects) we know about as they run on our cloud infra but our validator is also [on the Docker Hub](https://hub.docker.com/r/isaitb/shacl-validator) and is quite heavily used.

**Comment by costas80** [comment]
Hey @HolgerKnublauch . It would probably be best to split what we've been discussing here in two issues. The current one can focus on making a new release and the other one can be a discussion to see if and how the current repo can continue being maintained. Like that the second one will also get more visibility within the repo's users.

**Comment by griddigit** [comment]
I agree with Costas. It makes sense to split.
I see that we need to check with Andy if Jena SHACL covers SHACL-AF (Advanced Features), SHACL inferencing rules, node expressions and user-defined SPARQL functions and see if there is room to add those to Jena SHACL. Or do some sort of integration so that the additional stuff uses Jena SHACL as well in case not all is added in Jena.

**Comment by HolgerKnublauch** [comment]
After a very busy week I today finally had some time to do a new release.

I went with the long-term option instead of doing a patched release. So SHACL-JS is gone from 1.4.0 and it uses the same code that we also use in the product. This means that moving forward I can more easily keep things alive.

Would be good to get confirmation that the binaries that I have uploaded actually work?
