### ISSUE TITLE
Custom message for sh:xone

### ISSUE THREAD

**Issue by nvitucci** [TopQuadrant/shacl#14]
Is it possible to show the message of the shape constraint that was violated within a `sh:xone`? Right now, even if I add a custom `sh:message` to each shape, I only get a generic `"Focus node has 0 of the shapes from the 'exactly one' list"`.

**Comment by HolgerKnublauch** [comment]
How would this work - if it has 0 of the shapes, then it would need to print all messages? And what would it do for the (common) case in which users did not specify a message? And what should happen if it conforms to 2 or more?

**Comment by nvitucci** [comment]
Let's break it down.

* When the shapes are 0 or at least 2, the "exactly one" constraint is the first violation; so, the `"Focus node has n of the shapes from the 'exactly one' list"` is appropriate. Then:
  * If there are 0 shapes it means that **all** the constraints have been violated, thus I think reporting each one of them separately would be more appropriate; in this case, if there are _n_ shapes in `sh:xone`, then _n + 1_ violations will be reported (on the `sh:XoneConstraintComponent` + each of its members).
  * If there are 2+ shapes there is no way to know which one is the "correct" one (if there is any at all), so the "general" message would probably be enough; still, in this case a custom message for the whole `sh:xone` group could be helpful (but I don't know whether it would be possible to add it with the existing syntax).
* When users do not specify a message for a shape, the default one is still good (it tells you at least what kind of violation occurred).

Does this make sense?

**Comment by HolgerKnublauch** [comment]
Note that a shape doesn't really have a default message. A shape may have multiple constraints (e.g. sh:minCount, sh:class, and each of them would produce different messages. To me this makes the whole approach difficult to implement. Instead of messages, you probably mean a "label" for the nested shapes, e.g. the URI or qname if the shape is an IRI. But then again, people can already learn about this by "clicking through" from the violation to the shape definition.

SHACL includes a mechanism using sh:details that is supposed to handle such scenarios better. Basically it would include the full nested validation results, i.e. report any violations that were produced as part of validating sh:xone. I believe creating those (as an option) would be a better solution than trying to cramp so much info into a sh:resultMessage. The same approach would then apply to sh:node, sh:and etc. It would require a more sophisticated error display however.

**Comment by nvitucci** [comment]
I saw the `sh:detail` in the documentation and actually it could be a viable solution, but I am not sure it is already implemented. Is it? Any examples of its (intended) behaviour?

**Comment by HolgerKnublauch** [comment]
No it's not implemented yet. But an example would be if you have a nested shape such as sh:node, then sh:details would point at all validation results produced by the "nested" validation.

I will leave this ticket here open until I had time to work on these. It would become a flag (or users can select for which components they want details). There are lots of moving pieces right now so I cannot tell when this will be done. If you need them urgently yourself, it's open source...

**Comment by nvitucci** [comment]
Sure, no problem. I am now trying all the currently available features of SHACL with a running example, so I'll keep giving feedback.

**Comment by benellefi** [comment]
Dear Holger,

Could you pls give us an example of **sh: detail** as it seems to be the only messaging solution for nested shapes via sh:Node. Thank you !
