### ISSUE TITLE
Support for serialization formats other than Turtle?

### ISSUE THREAD

**Issue by wkjds** [TopQuadrant/shacl#146]
Are there plans to introduce support for serialization formats other than Turtle?

**Comment by HolgerKnublauch** [comment]
I guess you are referring to the command line tools. This currently only supports Turtle, but other programmatic use may of course use Jena Models loaded by other means and serializations.

Moving forward, I personally do not have plans to make further changes to this repo because it has diverged quite a bit from the code base that we use in the product, and SHACL is now supported by many other libraries including built-in support for Jena.

However, it is an open source project that anyone can fork off and continue changes.

**Comment by afs** [comment]
https://jena.apache.org/documentation/shacl/
