### ISSUE TITLE
Querying an endpoint via SPARQL generated by the SHACL engine 

### ISSUE THREAD

**Issue by Chaza** [TopQuadrant/shacl#17]
Hi there and thanks for this amazing open source product,

I was wondering if there is a possibility to query an endpoint via the SHACL engine (and how, if so)? I believe this engine converts the rules/shapes to SPARQL in some way to query datasets internally, am I correct? If this is the case, then it should also be possible to query external databases/endpoints using the same engine.

**Comment by HolgerKnublauch** [comment]
Hi and thanks for your feedback. Querying end points directly is not supported with the current architecture. It would require a different mechanism than the pre-binding approach that we currently take. For example, we currently execute some query that takes $minCount as a parameter. Instead of pre-binding we would need to insert the value into the query. This is not always possible (bnodes).

There is a theoretical possibility to use the SHACL API against a SPARQL endpoint if we you wrap that endpoint into a Jena Graph, i.e. translate all find(S,P,O) calls into corresponding SELECT ?s ?p ?o queries.

But for a properly working endpoint engine, a different algorithm would be needed and we have no plans to implement that in the foreseeable future. Plenty of room for open source projects...
