### ISSUE TITLE
Severity is ignored

### ISSUE THREAD

**Issue by m0squito** [TopQuadrant/shacl#26]
It seems that the `sh:severity` assertion is ignored in the shapes. Regardless of the value for this assertion, the validation report always shows `sh:Violation`.

You can test it with the example described [here](https://www.topquadrant.com/technology/shacl/tutorial-sparql-constraints/).

**Comment by HolgerKnublauch** [comment]
The example that you have pointed out was outdated, and its statement at the end misleading. I have now updated that page. Apologies for that delay.

Earlier drafts of SHACL included the ability to set sh:severity for each sh:sparql constraint. But that got simplified away, and now sh:severity is only supported at the shape itself. Is that what you tried too? When I try this with the latest snapshot (bundled with TopBraid 5.4) I do get the warning reported correctly. If not, could you send exactly what you have tried?

**Comment by m0squito** [comment]
@HolgerKnublauch you are right -- once the `sh:severity` is moved up to the node shape, it works as expected. 

I think the example is still outdated. You don't have to import DASH - it's not used anywhere in the code. Also, the SHACL Schema link is outdated. Finally, I don't think the prefixes declaration is done properly. At least, it didn't work for me until I made a few changes - [this Turtle code](https://github.com/TopQuadrant/shacl/files/1319631/hotels.txt) that I ran against the API.

Does the change of `sh:severity` usage mean that if I have a node shape with multiple property shapes and I want to specify a different severity for each of them, I have to create a separate node shape for each property shape?

**Comment by HolgerKnublauch** [comment]
DASH is imported by default - it serves as a wrapper of the SHACL namespace and includes the validators used by TopBraid. It's unnecessary in theory and the SHACL API will internally apply the import of DASH if missing. The schema link is outdated but I have left it in because that's how TopBraid 5.3 currently works (it has its own copy of that namespace). Future versions may use the SHACL schema.org version instead.

The prefix declaration does work for me, but it's easy to get things slightly wrong. If you can send me the version that did not work for you, I could try and hunt down a problem.

Property shapes can still carry their own sh:severity, so you would only need multiple node shapes if you want multiple sh:sparql constraints with different severity.

**Comment by m0squito** [comment]
Prefixes are all done properly, I edited my previous response. I realized the `sh:prefixes` imports entire RDF node with declarations inside. Initially, I thought I had to make a `?s sh:prefixes ?prefix` statement for each `?prefix`.

Thanks a lot for quick responses! The issue is resolved for me ;-)
