### ISSUE TITLE
More verbose validation result output for OR constraint

### ISSUE THREAD

**Issue by cmader** [TopQuadrant/shacl#4]
Having defined a shape including an OR constraint, when validation fails for one of the shapes in this constraint, the validation result model does not point me to the sub-constraint that actually failed. Would be nice to include a ValidationResult individual also for the failing sub-constraint.
Background is I'm performing some repair strategies on the identified violations and therefore I need to know what predicate is responsible for the failure.

**Comment by HolgerKnublauch** [comment]
Yes fully agreed, this should happen at some stage. Right now the implementation tries to be as simple as possible. To add nested violation results we have sh:detail in the spec, and the implementation would need to be changed to hard-code OR (and sh:valueShape and a few other places) so that they work differently. While SHACL is unstable, I have no immediate plans to make these changes, but it should definitely be done.

**Comment by HolgerKnublauch** [comment]
Just closing old tickets that have no immediate follow-up actions. In this case, the API has changed a lot since the question was asked.
