### ISSUE TITLE
SHACL as Apache Jena Reasoner

### ISSUE THREAD

**Issue by barrynl** [TopQuadrant/shacl#44]
Hi everybody, 

I'm interested in using the rule reasoning capabilities of this SHACL implementation in our project, but I have a two questions:

- I assumed this reasoner would utilize [Apache Jena's Reasoner API](https://jena.apache.org/documentation/inference/index.html), but I cannot, for example, find the org.apache.jena.reasoner.Reasoner interface used anywhere in this repository. Is my assumption incorrect and does this project only use Apache Jena for handling RDF data and not for hooking up the reasoner to an InfModel?
- Does this SHACL rule reasoner support backwards or goal-oriented reasoning?

Thanks in advance!

Barry

**Comment by HolgerKnublauch** [comment]
Hi Barry,
the current SHACL API does not support the Jena Reasoner API, but I think it could be done quite easily, assuming it is acceptable to pre-compute all inferences into a deductions graph. This is because SPARQL-based SHACL rules are too expressive to support backward chaining and therefore for the general case the engine would first need to apply all rules and then store the inferred triples in an auxiliary graph. This is basically what the current example implementations (see RuleUtil.executeRulesHelper) already does, and wrapping this into InfModel should be straight-forward. While I have no plans to implement such a wrapper myself, I certainly welcome contributions.

Now the topic of backwards chaining. Parts of sh:TripleRules could already be supported using backward chaining, because the language is much less expressive than general SPARQL-based rules. In fact I am currently working on an extended version of triple rules with a more convenient mechanism to attach rules to property shapes, to make the contract of these rules more explicit. I am not yet ready to make this work public but plan to do that here in the next couple of weeks. We are currently in internal discussions on how to best expose this type of inferencing, and one alternative would be to expose such queries via SPARQL, or even as Jena Graphs. I need a bit more time to bring this to a stable state but will get back to you.

As input, would you be able to summarize the kinds of expressiveness that you're after for your project? Are the rules SPARQL-based with "complex" operations or would less be sufficient?

**Comment by HolgerKnublauch** [comment]
I had promised to update you when the new backward chaining has been published, and it has now been merged into master. See https://twitter.com/HolgerKnublauch/status/1039060401848168448

**Comment by barrynl** [comment]
Thanks, that's quick!
