### ISSUE TITLE
Alow specifying ontological rules in shape file

### ISSUE THREAD

**Issue by retog** [TopQuadrant/shacl#48]
With entailment set to http://www.w3.org/ns/entailment/RDFS a statement specifying that one class is a subClassOf another only has its effect when specified in the data graph, it would be nice if this could also be specified in the shape graph or alternatively in a separate ontology file.

**Comment by HolgerKnublauch** [comment]
As the SHACL standard only covers sh:entailment on the data graph, this would need to be some custom mechanism. Since the shapes graph here is just a Jena Graph object, couldn't you just activate the inferencing in the calling code when you pass in the shapes graph? You could for example materialize the inferred triples beforehand, or use the Jena reasoner API. If this doesn't work, what would you suggest on the SHACL API level?

**Comment by retog** [comment]
I'm not suggesting entailment on the shape graph but to use the shape graph as t-box data. In my use case I'm using the command line tool to validate data for compliance with a standard.

**Comment by HolgerKnublauch** [comment]
In many use cases in TopBraid, the data graph = shapes graph. In the API, you have the choice to either do the same or make the shapes graph a subgraph (Jena MultiUnion) of the data graph. There is nothing wrong with that.

On whether rdfs:subClassOf should in general be queried in the shapes graph, this would complicate the logic of each query including those that operate on rdf:type triples (instances). Also it would make shapes graphs identical to data graphs for all use cases where people define custom subclasses in their ontologies (e.g. to extend an existing ontology). Anyway, this topic is water down the bridge and I would need to remind myself of the details of that discussion from the data shapes mailing list and meeting records.
