### ISSUE TITLE
shaclc->shacl outputs `;` instead of `.`

### ISSUE THREAD

**Issue by VladimirAlexiev** [TopQuadrant/shacl#91]
Hi @HolgerKnublauch !

I have this test file: `property-2-values-and.shacl`:
```ttl
@base <http://example.org/property-or-2> .
@prefix ex: <http://example.org/test#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<>
	a owl:Ontology ;
.

ex:TestShape
	a sh:NodeShape ;
	sh:property [
		sh:path ex:property1 ;
		sh:hasValue ex:value1 ;
	] ;
	sh:property [
		sh:path ex:property1 ;
		sh:hasValue ex:value2 ;
	] ;
.
```

Then I convert it to SHACL using code by @yasengmarinov (we plan to release it shortly):
```java
    shaclcWriter.write(
        getOutputStream(), RDFDataMgr.loadGraph(inputFile, TURTLE), new PrefixMapStd(), BASE, null);
```

The result is `property-2-values-and.shaclc`:
```
BASE <http://example.org/>

shape ex:TestShape {
	ex:property1  [0..*] hasValue=ex:value2 ;
	ex:property1  [0..*] hasValue=ex:value1 ;
}
```

And has two problems:
- line endings are `;` but should be `.`
- the `PREFIX`-es are missing

Trying to parse this as SHACLC returns these errors:
```
line 4:41 token recognition error at: ';'
line 5:41 token recognition error at: ';'
line 6:0 mismatched input '}' expecting {'Literal', '{', 'maxLength', 'qualifiedMaxCount', 'deactivated', 'qualifiedMinCount', 'maxExclusive', 'languageIn', 'minLength', 'equals', 'hasValue', '@', 'BlankNodeOrLiteral', 'datatype', 'qualifiedValueShape', 'disjoint', 'message', 'IRI', 'BlankNodeOrIRI', 'closed', 'nodeKind', 'severity', 'qualifiedValueShapesDisjoint', 'class', 'uniqueLang', 'maxInclusive', 'flags', 'lessThan', '.', 'minInclusive', '[', 'ignoredProperties', 'IRIOrLiteral', '|', 'pattern', '!', 'in', 'minExclusive', 'BlankNode', 'lessThanOrEquals', IRIREF, PNAME_NS, PNAME_LN, ATPNAME_NS, ATPNAME_LN}
Exception in thread "main" java.lang.RuntimeException: Undefined prefixed name ex:TestShape
```

**Comment by HolgerKnublauch** [comment]
Hi Valdimir, I am very glad to see some interest in SHACLC. I needed some down-time this weekend and didn't yet have a chance to get to your questions, but will try to reach them in the next few days. Apologies for the delay.

**Comment by HolgerKnublauch** [comment]
The prefixes are empty because your code just uses new PrefixMapStd() which is empty I guess.

You are right about the ; which was a left-over from previous versions of the spec. I have changed it to '.' hopefully resolving this ticket.

Note that the SHACLC writer is really just a toy and will not work for many if not most real SHACL files. I regard the Compact Syntax as a decent way of getting definitions INTO a system, but not as an output format.

**Comment by VladimirAlexiev** [comment]
> Compact Syntax .. not as an output format.

Compact is 3x briefer than Normal and much nicer to work with, not least because the ANTL grammar gives useful error messages, which can be used to highlight errors eg in Emacs flycheck.

So if I get a bunch of Normal files and need to edit them, I'd first convert to Compact. I think this inverse conversion is also useful.

**Comment by HolgerKnublauch** [comment]
Yes, the Antlr argument is valid during editing, and that's perfectly fine. Quickly drafting shape trees is good with the compact syntax.

I meant the case where you have no SHACLC to begin with and need to edit that. Once you convert them to SHACLC you'll possibly loose triples because SHACL is much richer than that.

**Comment by VladimirAlexiev** [comment]
closing this, making a new one for the leftover issues
