### ISSUE TITLE
hasValue twice?

### ISSUE THREAD

**Issue by VladimirAlexiev** [TopQuadrant/shacl#93]
I'm trying to enforce that a certain property has 2 particular values (conjunction, not the disjunction of `in`).

Can I do it with this SHACL ?
```ttl
ex:TestShape
	a sh:NodeShape ;
	sh:property [
		sh:path ex:property1 ;
		sh:hasValue ex:value1 ;
	] ;
	sh:property [
		sh:path ex:property1 ;
		sh:hasValue ex:value2 ;
	] ;
.
```

This SHACLC:
```
PREFIX ex: <http://example.org/test#> 
PREFIX sh: <http://www.w3.org/ns/shacl#> 

shape ex:TestShape {
	ex:property1  [0..*] hasValue=ex:value2 .
	ex:property1  [0..*] hasValue=ex:value1 .
} 
```

converts to this SHACL, which has just one of the values:
```ttl
ex:TestShape  a      sh:NodeShape ;
        sh:property  []  ;
        sh:property  [ sh:hasValue  ex:value2 ;
                       sh:path      ex:property1
                     ] . 
```

Two related questions:
- if the property is `rdf:type`, is there a quicker way?
- I noticed that SHACLC doesn't have syntax for `sh:and`, is that related? (Also doesn't have `sh:xor`)

Thanks in advance!

**Comment by HolgerKnublauch** [comment]
The blank node issue works for me. Maybe the same problem as the other ticket. Are you using an in-memory Jena Graph for runtime? I am asking because some Graph implementations don't preserve blank node identity and thus subsequent requests against the same bnode return another instance.

To express that a property must have two values, I think you can just do

`ex:TestShape
	a sh:NodeShape ;
	sh:property [
		sh:path ex:property1 ;
		sh:hasValue ex:value1 ;
		sh:hasValue ex:value2 ;
	] ;
.`

because sh:hasValue is just an EXISTS { ?focusNode ex:property1 $hasValue }.

For rdf:type maybe you mean sh:class semantics, which would also walk up the class hierarchy.

sh:and is generally unnecessary and therefore not supported by SHACLC. Doing X sh:and (A B) is equivalent to simply saying X sh:node A, B. sh:and was only included into the spec for symmetry reasons, but I think it would have been better to just drop it.

**Comment by HolgerKnublauch** [comment]
Closing old ticket.
